"""empty message

Revision ID: 267cbf583d49
Revises: fdd28027966c
Create Date: 2020-04-02 10:25:24.509904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267cbf583d49'
down_revision = 'fdd28027966c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_forestilling_prod_nr'), 'forestilling', ['prod_nr'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forestilling_prod_nr'), table_name='forestilling')
    # ### end Alembic commands ###
