"""empty message

Revision ID: fdd28027966c
Revises: 
Create Date: 2020-03-25 10:19:48.360294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd28027966c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forestilling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forestilling_navn', sa.String(length=120), nullable=True),
    sa.Column('premiere', sa.DateTime(), nullable=True),
    sa.Column('prod_nr', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forestilling_forestilling_navn'), 'forestilling', ['forestilling_navn'], unique=False)
    op.create_index(op.f('ix_forestilling_premiere'), 'forestilling', ['premiere'], unique=False)
    op.create_index(op.f('ix_forestilling_prod_nr'), 'forestilling', ['prod_nr'], unique=False)
    op.create_table('trekk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trekknummer', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trekk_trekknummer'), 'trekk', ['trekknummer'], unique=True)
    op.create_table('loft_element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_navn', sa.String(length=64), nullable=True),
    sa.Column('trekk_id', sa.Integer(), nullable=True),
    sa.Column('posisjon', sa.String(length=140), nullable=True),
    sa.Column('paaskjot', sa.String(length=120), nullable=True),
    sa.Column('ekstra_info', sa.String(length=140), nullable=True),
    sa.Column('forestilling_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['forestilling_id'], ['forestilling.id'], ),
    sa.ForeignKeyConstraint(['trekk_id'], ['trekk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loft_element_element_navn'), 'loft_element', ['element_navn'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loft_element_element_navn'), table_name='loft_element')
    op.drop_table('loft_element')
    op.drop_index(op.f('ix_trekk_trekknummer'), table_name='trekk')
    op.drop_table('trekk')
    op.drop_index(op.f('ix_forestilling_prod_nr'), table_name='forestilling')
    op.drop_index(op.f('ix_forestilling_premiere'), table_name='forestilling')
    op.drop_index(op.f('ix_forestilling_forestilling_navn'), table_name='forestilling')
    op.drop_table('forestilling')
    # ### end Alembic commands ###
